# Generated by Django 4.2.14 on 2024-09-30 22:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='phone_number',
            field=models.CharField(blank=True, default='1234567890', max_length=20, null=True),
        ),
    ]
