# Generated by Django 4.2.14 on 2024-09-13 13:20
# migrations/0006_migrate_cartitems.py

from django.db import migrations


def migrate_cartitems(apps, schema_editor):
    CartItem = apps.get_model('cart', 'CartItem')
    ContentType = apps.get_model('contenttypes', 'ContentType')
    Product = apps.get_model('cart', 'Product')
    Device = apps.get_model('cart', 'Device')

    for item in CartItem.objects.all():
        if item.content_type.model == 'product':
            item.product_id = item.object_id
        elif item.content_type.model == 'device':
            item.device_id = item.object_id
        item.save()

class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0005_order_orderitem'),
    ]

    operations = [
        migrations.RunPython(migrate_cartitems),
    ]
