# Generated by Django 4.2.14 on 2024-09-13 14:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0006_auto_20240913_0820'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cartitem',
            name='content_type',
        ),
        migrations.RemoveField(
            model_name='cartitem',
            name='object_id',
        ),
        migrations.AddField(
            model_name='cartitem',
            name='device',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='cart.device'),
        ),
        migrations.AddField(
            model_name='cartitem',
            name='product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='cart.product'),
        ),
    ]
